chillometer/models/temperature.py
from mongoengine import Document, FloatField


class Temperature(Document):
    T_MIN = -20.0
    T_MAX = 50.0
    temperature = FloatField(required=True, min_value=T_MIN, max_value=T_MAX)

chillometer/__init__.py
from flask import Flask, Response
from chillometer.database import close_db

DEFAULTS = {
    "MONGODB_DB": "chillometer"
}

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_mapping(test_config or DEFAULTS)
    app.teardown_appcontext(close_db)

    from .views import main

    app.register_blueprint(main.bp)

    return app

chillometer/views/main.py
from flask import Blueprint, render_template, make_response, abort, request
from werkzeug.exceptions import HTTPException
from ..database import get_db

from ..models.temperature import Temperature

bp = Blueprint("main", __name__)


@bp.errorhandler(HTTPException)
def handle_exception(e):
    """Return JSON instead of HTML for HTTP errors."""
    resp = {
        "code": e.code,
        "name": e.name,
        "description": e.description,
    }
    return make_response(resp, e.code)


@bp.route("/")
def index():
    return render_template("index.html")


@bp.route("/manual")
def manual():
    return render_template("index.html")


@bp.route("/privacy")
def privacy():
    return render_template("index.html")


@bp.route("/legal")
def legal():
    return render_template("index.html")


@bp.route("/<int:id>/thermometer.svg")
def thermometer(id):
    if id != 0:
        abort(404, description="Temperature ID not found.")
    get_db()
    entry = Temperature.objects().first()
    if entry is None:
        t = -20.0
    else:
        t = entry.temperature
    t = max(Temperature.T_MIN, min(Temperature.T_MAX, t))
    resp = make_response(render_template("thermometer.svg", celsius=t))
    resp.headers["Content-type"] = "image/svg+xml; charset=utf-8"
    return resp


@bp.route("/api/v1.0/temperature/<int:id>", methods=["PUT"])
def update_temperature(id):
    if id != 0:
        abort(404, description="Temperature ID not found.")
    if not request.json:
        abort(400, description="Request must contain JSON.")
    if not "temperature" in request.json:
        abort(400, description="Missing JSON field 'temperature'.")
    json = request.json
    try:
        t = float(json["temperature"])
    except ValueError:
        abort(
            400,
            description="Failed to parse JSON field 'temperature', should be a float number.",
        )
    get_db()
    entry = Temperature.objects().first()
    if entry is None:
        entry = Temperature(temperature=t)
    else:
        entry.temperature = t
    entry.save()
    return {"temperature": t}

chillometer/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='classless.css') }}">
    <title>Chill-o-meter</title>
</head> 

<body>
    <header>
        <nav>
            <ul>
                <li>Brand</li>
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.manual') }}">Manual</a>
                <li><a href="{{ url_for('main.privacy') }}">Privacy / Datenschutz</a></li>
                <li class="float-right"><a href="{{ url_for('main.legal') }}">Legal Notice / Impressum</a></li>
            </ul>
        </nav>
        {% block header %}{% endblock %}
    </header>
    {%- block content %}{% endblock -%}
</body>

<footer class="bg-light">
    <section>
        <h5>Chill-o-meter</h5>
        Code on <a href="https://bitbucket.org/skoe/chillometer">Bitbucket</a>.
    </section>
</footer>

</html>

chillometer/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Chill-o-meter!</h1>
    <img src="{{ url_for('main.thermometer', id=0) }}" alt="Thermometer">
{% endblock %}